### ISSUE TITLE
dataset!

### ISSUE THREAD

**Issue by Dhr-Lqq** [zhysora/PGMAN#1]
你好，为什么我下载你提供多个数据集，里面.tif格式的图像都是黑白的？

**Comment by zhysora** [comment]
相应的PAN.tif应该是灰度图像，MUL.tif是多光谱图像

**Comment by Dhr-Lqq** [comment]
你好，谢谢你的回复！
        图像打开时候时候，请问你是用什么方式打开的呢？我直接print读取的PAN.tif时，显示是1和0整数值，而且我用cv2读取成bgr时也时全黑的。但实验正常进行。我在想我是不是读取方式有问题。

**Comment by zhysora** [comment]
应该使用专业的遥感图像软件打开，遥感图像的位深都是11-bit，12-bit之类的。我一般使用ENVI或者ArcMap

**Comment by Dhr-Lqq** [comment]
收到，谢谢！我试一下。

**Comment by Dhr-Lqq** [comment]
![Test-0-PAN-TIF](https://user-images.githubusercontent.com/74961490/115105960-8a590c80-9f94-11eb-9a54-1fc5b17318d6.png)
你好，这是我用ENVI打开的QK原始测试集0-PAN.tif文件，显示全白。然而测试结果图片（0_mul_hat.tif）可以用envi正常打开，请问是什么原因导致的啊？ 另外，我可以加一下你的VX吗？或者你加一下我的vx（17371090913），最近在学习你的代码。
