### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by oceannmoon** [zhysora/PGMAN#10]
您好，请问数据集制作时的handle_raw.py和gen_dataset.py文件中，dic = {'QB' : 5, 'GF-2' : 6, 'WV-3' : 3}中GF-2数据集的张数不一致，按照给出的代码得到的patch和文章中的数据不同，这个是需要修改的吗？对模型的训练有没有影响？谢谢！

**Comment by zhysora** [comment]
按照实际的数据集中的张数进行调整即可
