### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by sxdeivm** [zhysora/PGMAN#11]
您好，我下载了PSData3_Raw文件，可是运行handle_raw.py文件时，发生了错误，
![image](https://user-images.githubusercontent.com/90969358/229703496-fd12e2a0-8fe5-4364-af7c-e5de2c65a7c4.png)
请问这个文件夹应该解压到哪里呢？还有WV-8band文件夹的内容是干什么的，要放到那个文件夹呢？非常感谢您的回答（渴望）

**Comment by zhysora** [comment]
需要将这里的代码，改成你对应解压到的路径。你通过错误信息也可以发现目前的路径是不正确的
https://github.com/zhysora/PGMAN/blob/fe01ce8f4a09cd4c10fa5dd31dcc240041e2c3fd/data/handle_raw.py#L11
WV-8band里面就是WV-3卫星8通道的tif图片

**Comment by sxdeivm** [comment]
源文件的路径：
.
但还是报错，路径没问题啊，着应该咋改才正确呢，跪谢





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhysora/PGMAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月4日(星期二) 下午3:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhysora/PGMAN] 数据集 (Issue #11)





 
需要将这里的代码，改成你对应解压到的路径。你通过错误信息也可以发现目前的路径是不正确的
 https://github.com/zhysora/PGMAN/blob/fe01ce8f4a09cd4c10fa5dd31dcc240041e2c3fd/data/handle_raw.py#L11
 WV-8band里面就是WV-3卫星8通道的tif图片

**Comment by sxdeivm** [comment]
可以了，我输入绝对路径就能运行了，感谢您的回答


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhysora/PGMAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月4日(星期二) 下午3:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhysora/PGMAN] 数据集 (Issue #11)





 
需要将这里的代码，改成你对应解压到的路径。你通过错误信息也可以发现目前的路径是不正确的
 https://github.com/zhysora/PGMAN/blob/fe01ce8f4a09cd4c10fa5dd31dcc240041e2c3fd/data/handle_raw.py#L11
 WV-8band里面就是WV-3卫星8通道的tif图片

**Comment by sxdeivm** [comment]
您好，我想问一下运行完run.py就能出融合结果是吗？（已运行完成data/handle_raw.py和data/gen_dataset.py）（但是我找半天没找到融合结果在哪里啊）跪谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhysora/PGMAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月4日(星期二) 下午4:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhysora/PGMAN] 数据集 (Issue #11)





 
Closed #11 as completed.
