### ISSUE TITLE
请教eval.py

### ISSUE THREAD

**Issue by Dhr-Lqq** [zhysora/PGMAN#2]
您好！对于您代码中eval.py中的开头test_cnt, row, col, bit这些参数能详细介绍一下吗？是如何设置的？非常需要您的帮助。谢谢！

**Comment by zhysora** [comment]
test_cnt：测试样本数
row：裁剪图像的行数
col：裁剪图像的列数
bit：图像的位深度
这些参数是根据测试集的生成方式决定的

**Comment by Dhr-Lqq** [comment]
谢谢您的回复
