### ISSUE TITLE
--mode参数

### ISSUE THREAD

**Issue by Summer587** [zhysora/PGMAN#5]
感谢您提供的代码，我有一些问题想请教一下：
1、怎样设置参数—mode来控制模型是在全分辨率下训练（PGMAN(F)）还是在低分辨率下训练（PGMAN(W)）。
2、QB和GF-2训练样本数为多少比较合适。
3、我在跑代码时出现损失函数为负值的情况不知道您是否遇到过。

**Comment by zhysora** [comment]
1. 参见main.py 68行，"pgman"会在低分辨率下训练，"pgman-2"会在全分辨率下训练
2. 看原始图像的大小和划分块的大小，一般每张图随机取4000～5000个patch
3. 如果是对抗损失负值很正常，WGAN-GP的loss本来就可以是负的
