### ISSUE TITLE
eval_one.py 请教

### ISSUE THREAD

**Issue by Dhr-Lqq** [zhysora/PGMAN#6]
您好！在您的eval_one.py中，如何计算test_full_res的评价指标？ 在计算test_low_res的评价指标时，因为测试集中有n_mul.tif图像，但是test_full_res中并没有n_mul.tif图像, 对于full图像的评价指标如何在代码中求得？ 谢谢您！

**Comment by zhysora** [comment]
test_full_res只计算non-reference指标，non-referecne指标不需要GT图像，详见eval_one.py

**Comment by Dhr-Lqq** [comment]
您好！谢谢您的回复。但是您论文中的full图像的评价指标在没有参考图像时时如何计算的呢？我看您论文中不仅有low图像的评价指标，还有full图像的全部评价指标。

**Comment by zhysora** [comment]
full图像的指标只用D_lambda, D_s, QNR，不用参考图像

**Comment by Dhr-Lqq** [comment]
可能是我论文没有看透，在代码中我理解您的意思，full图像只有QNR等三个指标。但是论文中您列举的这些数值，请问是如何得到的，在没有参考图像的情况下。见图最后一行。
![指标](https://user-images.githubusercontent.com/74961490/119344907-d2bdc580-bcca-11eb-94be-f388bcdae9b0.png)

**Comment by zhysora** [comment]
其他指标就是在test_low_res上侧的，这一行代表模型是在full图像上训练，测试的时候既在low上测，也在full上测

**Comment by Dhr-Lqq** [comment]
非常感谢您的解答！谢谢！
