### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by rc998** [zhysora/PGMAN#7]
您好，我是一个图像融合的初学者，您这是我第一份见到的pytorch的代码，非常的清晰规范，我想向您请求一下您在models中提供pytorch版本的其他代码（如psgan、pannet等），不知道您是否方便。我保证仅限个人学习使用，如果方便的话，我留下我的邮箱：3312256349@qq.com，冒昧打扰，十分抱歉。祝好！

**Comment by zhysora** [comment]
你说的这些代码应该都是有官方实现版本的
